sudo: required

git:
  submodules: false

language: java

services:
  - docker

jdk:
  - oraclejdk8

script: 
  - mvn test
  - docker build -t $DOCKER_HUB_REP .

deploy:
	provider: azure_web_apps
	username: $azure_deployment_user
	password: $azure_deployment_password
	site: $azure_deployment_sitename

